name = "flaxia-sandbox"
main = "src/sandbox-worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "sandbox.flaxia.app/*", zone_name = "flaxia.app" }
]

[assets]
directory = "./sandbox"
binding = "ASSETS"
run_worker_first = true

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "flaxia-content"


[[d1_databases]]
binding = "DB"
database_name = "flaxia"
database_id = "7c99f35f-69a0-4644-96a1-34c716a3e82d"

[[kv_namespaces]]
binding = "CACHE"
id = "c78f7711cd9d45738678474d884734c1"
