-- Personal vault (docs/e2ee.md).
--
-- Every byte in these tables is opaque to the server: VK, item keys and
-- payloads are produced client-side and the server has no key that can open
-- them. Columns therefore store base64 ciphertext, never key material.
--
--   password ──PBKDF2──► KEK ─┐
--   recovery phrase ──PBKDF2──► REK ─┤─wrap─► VK ─wrap─► item_key ─AES-GCM─► payload
--   device key (IndexedDB) ──────────┘
--
-- recovery_salt is separate from salt on purpose: a user who chooses their
-- password as their recovery phrase would otherwise produce one envelope
-- instead of two independent paths.

CREATE TABLE IF NOT EXISTS vault_keys (
  user_id       TEXT PRIMARY KEY,
  salt          TEXT NOT NULL,
  recovery_salt TEXT NOT NULL,
  kdf_params    TEXT NOT NULL, -- JSON: {"alg":"PBKDF2-SHA256","iterations":600000}
  wrapped_vk    TEXT NOT NULL, -- base64(iv).base64(ct), KEK-wrapped VK
  recovery_blob TEXT NOT NULL, -- base64(iv).base64(ct), REK-wrapped VK
  vk_version    INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- One row per approved device. Losing a device means deleting its row; a
-- stronger revocation rotates VK and re-wraps every item key (payloads are
-- never rewritten).
CREATE TABLE IF NOT EXISTS device_keys (
  id           TEXT PRIMARY KEY,
  user_id      TEXT NOT NULL,
  label        TEXT NOT NULL,
  wrapped_vk   TEXT NOT NULL,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  last_seen_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_device_keys_user_id ON device_keys(user_id);

-- id is generated by the client and is also the AAD of both crypto layers, so
-- a payload cannot be moved to another row without failing authentication.
CREATE TABLE IF NOT EXISTS vault_items (
  id                TEXT NOT NULL,
  user_id           TEXT NOT NULL,
  item_key_wrapped  TEXT NOT NULL,
  payload           TEXT NOT NULL,
  kind              TEXT NOT NULL,
  vk_version        INTEGER NOT NULL DEFAULT 1,
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (user_id, id)
);
