import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const buildDir = join(root, 'node_modules/pdfjs-dist/legacy/build');

// [source file in pdfjs-dist, exported constant in the generated module]
const EMBEDS = [
  ['pdf.min.mjs', 'PDFJS_MAIN_MJS'],
  ['pdf.worker.min.mjs', 'PDFJS_WORKER_MJS'],
];

/** Escape a source so it survives verbatim inside a template literal. */
function escapeForTemplate(source) {
  return source.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

try {
  const parts = EMBEDS.map(([file, name]) => {
    const content = readFileSync(join(buildDir, file), 'utf-8');
    return { name, escaped: escapeForTemplate(content), size: content.length };
  });

  const ts = `// Auto-generated by scripts/embed-pdfjs.mjs — do not edit manually
// pdf.js (https://mozilla.github.io/pdf.js/) — copyright Mozilla Foundation,
// licensed under the Apache License, Version 2.0. The original Apache license
// headers are preserved inside the embedded strings below. Re-run
// \`npm run build:pdfjs\` after changing the pdfjs-dist dependency.
${parts.map((p) => `export const ${p.name}: string = \`${p.escaped}\`;`).join('\n\n')}
`;

  writeFileSync(join(root, 'src/lib/pdfjs.generated.ts'), ts, 'utf-8');
  console.log(`Generated src/lib/pdfjs.generated.ts (${parts.map((p) => `${p.name}: ${p.size}B`).join(', ')})`);
} catch (err) {
  console.error('Failed to embed pdf.js:', err);
  process.exit(1);
}
