name = "notif-stream"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "NOTIFICATION_STREAM"
class_name = "NotificationStream"

[[durable_objects.bindings]]
name = "CALL_STREAM"
class_name = "CallStream"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["NotificationStream"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["ChatStream"]

[[migrations]]
tag = "v3"
deleted_classes = ["ChatStream"]

[[migrations]]
tag = "v4"
new_sqlite_classes = ["CallStream"]

