// Auto-generated by Vite build — do not edit manually
export const SPA_HEAD_TAGS: string = "<link rel=\"stylesheet\" href=\"/assets/main-DXXOo1G_.css\" media=\"print\" onload=\"this.media='all';this.onload=null\">\n  <link rel=\"modulepreload\" crossorigin href=\"/assets/main-DurNDn03.js\">\n  <script type=\"module\" crossorigin src=\"/assets/main-DurNDn03.js\"></script>";
