// Auto-generated by Vite build — do not edit manually
export const SPA_HEAD_TAGS: string = "<link rel=\"stylesheet\" href=\"/assets/main-AuGHkzI6.css\" media=\"print\" onload=\"this.media='all';this.onload=null\">\n  <link rel=\"modulepreload\" crossorigin href=\"/assets/main-v15o9LQZ.js\">\n  <script type=\"module\" crossorigin src=\"/assets/main-v15o9LQZ.js\"></script>";
